"""Pydantic schemas for the CamBot TimelineScript planning protocol."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class TimelineActionType(str, Enum):
    """Supported high-level timeline actions generated by the top-level agent."""

    BASE_LONGITUDINAL = "base_longitudinal"
    BASE_ROTATE = "base_rotate"
    LIFT_DELTA = "lift_delta"
    ARM_INIT_POSE = "arm_init_pose"
    ARM_MOVE_DELTA = "arm_move_delta"
    ARM_MOVE_XYZ = "arm_move_xyz"
    WAIT = "wait"
    CHECKPOINT = "checkpoint"
    FOLLOW_MODE = "follow_mode"


class DeviceName(str, Enum):
    S3 = "s3"
    P4 = "p4"
    LOCAL = "local"


class ChannelName(str, Enum):
    BASE = "base"
    LIFT = "lift"
    ARM = "arm"
    SCHEDULER = "scheduler"
    VISION = "vision"


class FailStrategy(str, Enum):
    STOP_ALL = "stop_all"
    CONTINUE = "continue"


class VisionFailStrategy(str, Enum):
    STOP_ALL = "stop_all"
    CONTINUE = "continue"


class BBoxFormat(str, Enum):
    CXCYWH_NORM = "cxcywh_norm"


class LightColorTemperature(str, Enum):
    WARM = "warm"
    COOL = "cool"
    NEUTRAL = "neutral"


class LightIntensity(str, Enum):
    STRONG = "strong"
    MEDIUM = "medium"
    WEAK = "weak"


class LightAzimuth(str, Enum):
    FRONT = "front"
    SIDE = "side"
    BACK = "back"


class LightHeight(str, Enum):
    BOTTOM = "bottom"
    MIDDLE = "middle"
    TOP = "top"


class StrictBaseModel(BaseModel):
    """Base model that rejects misspelled fields in planner output."""

    model_config = ConfigDict(extra="forbid", use_enum_values=True)


class TimelineStartMixin(StrictBaseModel):
    """Shared scheduling fields for timeline actions and lighting entries."""

    id: str
    start_at_s: float | None = None
    start_after: list[str] = Field(default_factory=list)
    description: str

    @field_validator("id")
    @classmethod
    def id_must_be_non_empty(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("id must be non-empty.")
        return value

    @field_validator("start_at_s")
    @classmethod
    def start_time_must_be_non_negative(cls, value: float | None) -> float | None:
        if value is not None and value < 0:
            raise ValueError("start_at_s must be non-negative.")
        return value


class ActionBase(TimelineStartMixin):
    """Common fields for high-level timeline actions."""

    device: DeviceName
    channel: ChannelName
    timeout_s: float = 8.0
    blocking: bool = True

    @field_validator("timeout_s")
    @classmethod
    def timeout_must_be_positive(cls, value: float) -> float:
        if value <= 0:
            raise ValueError("timeout_s must be positive.")
        return value


class BaseLongitudinalParams(StrictBaseModel):
    distance_m: float
    speed_m_s: float


class BaseRotateParams(StrictBaseModel):
    angle_deg: float
    angular_speed_rad_s: float


class LiftDeltaParams(StrictBaseModel):
    delta_cm: float


class ArmInitPoseParams(StrictBaseModel):
    wait_first_s: float = 2.0


class ArmMoveDeltaParams(StrictBaseModel):
    front_cm: float = 0.0
    left_cm: float = 0.0
    up_cm: float = 0.0
    wrist_delta_deg: float = 0.0
    speed: float = 0.25
    target_t_rad: float | None = None


class ArmMoveXYZParams(StrictBaseModel):
    target_xyz_m: tuple[float, float, float]
    target_t_rad: float | None = None
    speed: float = 0.25


class WaitParams(StrictBaseModel):
    duration_s: float


class BaseLongitudinalAction(ActionBase):
    type: Literal[TimelineActionType.BASE_LONGITUDINAL]
    device: Literal[DeviceName.S3] = DeviceName.S3
    channel: Literal[ChannelName.BASE] = ChannelName.BASE
    params: BaseLongitudinalParams
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class BaseRotateAction(ActionBase):
    type: Literal[TimelineActionType.BASE_ROTATE]
    device: Literal[DeviceName.S3] = DeviceName.S3
    channel: Literal[ChannelName.BASE] = ChannelName.BASE
    params: BaseRotateParams
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class LiftDeltaAction(ActionBase):
    type: Literal[TimelineActionType.LIFT_DELTA]
    device: Literal[DeviceName.S3] = DeviceName.S3
    channel: Literal[ChannelName.LIFT] = ChannelName.LIFT
    params: LiftDeltaParams
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class ArmInitPoseAction(ActionBase):
    type: Literal[TimelineActionType.ARM_INIT_POSE]
    device: Literal[DeviceName.P4] = DeviceName.P4
    channel: Literal[ChannelName.ARM] = ChannelName.ARM
    params: ArmInitPoseParams = Field(default_factory=ArmInitPoseParams)
    timeout_s: float = 10.0
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class ArmMoveDeltaAction(ActionBase):
    type: Literal[TimelineActionType.ARM_MOVE_DELTA]
    device: Literal[DeviceName.P4] = DeviceName.P4
    channel: Literal[ChannelName.ARM] = ChannelName.ARM
    params: ArmMoveDeltaParams
    timeout_s: float = 10.0
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class ArmMoveXYZAction(ActionBase):
    type: Literal[TimelineActionType.ARM_MOVE_XYZ]
    device: Literal[DeviceName.P4] = DeviceName.P4
    channel: Literal[ChannelName.ARM] = ChannelName.ARM
    params: ArmMoveXYZParams
    timeout_s: float = 10.0
    on_fail: FailStrategy = FailStrategy.STOP_ALL


class WaitAction(ActionBase):
    type: Literal[TimelineActionType.WAIT]
    device: Literal[DeviceName.LOCAL] = DeviceName.LOCAL
    channel: Literal[ChannelName.SCHEDULER] = ChannelName.SCHEDULER
    params: WaitParams
    timeout_s: float = 1.0
    on_fail: FailStrategy = FailStrategy.CONTINUE


class FrameTolerance(StrictBaseModel):
    center_x: float = 0.05
    center_y: float = 0.05
    width: float = 0.08
    height: float = 0.10


class ExpectedFrame(StrictBaseModel):
    enabled: bool = True
    target_class: str = "person"
    target_id: str = "main_actor"
    bbox_format: Literal[BBoxFormat.CXCYWH_NORM] = BBoxFormat.CXCYWH_NORM
    bbox: tuple[float, float, float, float] = (0.5, 0.52, 0.35, 0.65)
    tolerance: FrameTolerance = Field(default_factory=FrameTolerance)


class TargetFrame(StrictBaseModel):
    target_class: str = "person"
    target_id: str = "main_actor"
    bbox_format: Literal[BBoxFormat.CXCYWH_NORM] = BBoxFormat.CXCYWH_NORM
    bbox: tuple[float, float, float, float] = (0.5, 0.52, 0.35, 0.65)
    tolerance: FrameTolerance = Field(
        default_factory=lambda: FrameTolerance(center_x=0.06, center_y=0.06, width=0.10, height=0.12)
    )


class ServoConfig(StrictBaseModel):
    max_iters: int = 8
    allow_base: bool = True
    allow_lift: bool = True
    allow_arm: bool = False

    @field_validator("max_iters")
    @classmethod
    def max_iters_must_be_positive(cls, value: int) -> int:
        if value <= 0:
            raise ValueError("servo.max_iters must be positive.")
        return value


class CheckpointAction(ActionBase):
    type: Literal[TimelineActionType.CHECKPOINT]
    device: Literal[DeviceName.LOCAL] = DeviceName.LOCAL
    channel: Literal[ChannelName.VISION] = ChannelName.VISION
    expected_frame: ExpectedFrame = Field(default_factory=ExpectedFrame)
    servo: ServoConfig = Field(default_factory=ServoConfig)
    timeout_s: float = 30.0
    on_vision_fail: VisionFailStrategy = VisionFailStrategy.CONTINUE


class FollowModeAction(ActionBase):
    type: Literal[TimelineActionType.FOLLOW_MODE]
    device: Literal[DeviceName.LOCAL] = DeviceName.LOCAL
    channel: Literal[ChannelName.VISION] = ChannelName.VISION
    duration_s: float = 5.0
    target_frame: TargetFrame = Field(default_factory=TargetFrame)
    servo: ServoConfig = Field(
        default_factory=lambda: ServoConfig(max_iters=50, allow_base=True, allow_lift=True, allow_arm=False)
    )
    timeout_s: float = 10.0
    on_fail: FailStrategy = FailStrategy.CONTINUE

    @field_validator("duration_s")
    @classmethod
    def duration_must_be_positive(cls, value: float) -> float:
        if value <= 0:
            raise ValueError("duration_s must be positive.")
        return value


TimelineAction = Annotated[
    Union[
        BaseLongitudinalAction,
        BaseRotateAction,
        LiftDeltaAction,
        ArmInitPoseAction,
        ArmMoveDeltaAction,
        ArmMoveXYZAction,
        WaitAction,
        CheckpointAction,
        FollowModeAction,
    ],
    Field(discriminator="type"),
]


class LightingPlanEntry(TimelineStartMixin):
    color_temperature: LightColorTemperature = LightColorTemperature.NEUTRAL
    intensity: LightIntensity = LightIntensity.MEDIUM
    azimuth: LightAzimuth = LightAzimuth.FRONT
    height: LightHeight = LightHeight.MIDDLE


class TimelineScript(StrictBaseModel):
    """Top-level agent output: timeline actions plus lighting intent."""

    name: str = "open_loop_with_checkpoint_and_lighting"
    version: Literal["2.0"] = "2.0"
    mode: Literal["timeline"] = "timeline"
    summary: str = "按时间轴执行拍摄动作，并提供画面检查和打光方案。"
    timeline: list[TimelineAction] = Field(default_factory=list)
    lighting_plan: list[LightingPlanEntry] = Field(default_factory=list)

    @field_validator("name")
    @classmethod
    def name_must_be_non_empty_without_spaces(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("name must be non-empty.")
        if any(char.isspace() for char in value):
            raise ValueError("name must not contain whitespace.")
        return value

    @model_validator(mode="after")
    def ids_and_dependencies_must_be_valid(self) -> "TimelineScript":
        ids: set[str] = set()
        for action in self.timeline:
            if action.id in ids:
                raise ValueError(f"Duplicate timeline id: {action.id}")
            ids.add(action.id)

        for action in self.timeline:
            missing = [dep for dep in action.start_after if dep not in ids]
            if missing:
                raise ValueError(f"Action {action.id} references missing start_after id(s): {missing}")

        light_ids: set[str] = set()
        for light in self.lighting_plan:
            if light.id in light_ids:
                raise ValueError(f"Duplicate lighting_plan id: {light.id}")
            light_ids.add(light.id)
            missing = [dep for dep in light.start_after if dep not in ids]
            if missing:
                raise ValueError(f"Lighting entry {light.id} references missing start_after id(s): {missing}")
        return self


def default_expected_frame() -> dict:
    """Return the protocol's default checkpoint frame target as JSON-serializable data."""

    return ExpectedFrame().model_dump()


def default_target_frame(duration_s: float | None = None) -> dict:
    """Return the protocol's default follow-mode target frame as JSON-serializable data."""

    _ = duration_s
    return TargetFrame().model_dump()


def default_lighting_plan() -> list[dict]:
    """Return the required default lighting intent when the user did not specify one."""

    return [
        LightingPlanEntry(
            id="light_default",
            start_at_s=0.0,
            description="默认中性光、中等强度、正面中光。",
        ).model_dump()
    ]
